AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template to Create an S3 Bucket'

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
